U10: The player can discard an item of his choice from his hand
sopra-fs24-group-26/client pull request #101
Opened 2024-05-01 15:46 UTC by paul891112

I wasnt able to implement discarded locally, because to differentiate Drawn and Discarded state in ping data locally, the only way is to keep track of all discarded tiles locally. However, the record will get lost if I refresh the page.

To solve this problem, i make backend keep track of a boolean attribute "discarded" which evaluates to true if the tile is discarded. Also adjust code everywhere to match the change.

2024-05-02 11:26 UTC, Croxsy commented
> I could do option 1 because its easier to implement
> 
> Do you mean place it "over" the bottom right corner of tile?
> 
> And no, sorry i couldnt find any icon without background, all the images are downloaded in square shape, all i can do is minimize the white background.

Yeah I mean over:) Okay so we'll do an trash icon ourselfes

2024-05-04 09:16 UTC, paul891112 commented
Set tile state to Discarded is now done in backend, frontend just makes the call and receives tile information from ping

2024-05-05 21:29 UTC, C0DECYCLE approved these changes
Also sorry here for the delay. I did test everything, works super. Code looks also very good only 2 minor things inside the uiscreen.

2024-05-05 21:29 UTC, C0DECYCLE commented on src/scenes/gameuiscreen.ts
> +            //y = tileCoordinateY + tilePixels/2 - trashcanPixels/2
i think does comments are not necessary

2024-05-05 21:29 UTC, C0DECYCLE commented on src/scenes/gameuiscreen.ts
> +            );
we could use the built in interactify utils function here

2024-05-05 21:30 UTC, C0DECYCLE requested changes
Sorry accidentally selected the wrong field.

2024-05-06 07:50 UTC, merged