U03: A new player is only able to join in the lobby
sopra-fs24-group-26/client pull request #102
Opened 2024-05-02 12:42 UTC by Croxsy

added an if statement into join, that if the server doesnt return null then the playerId and everything is saved. Otherwise it returns (client goes then to titlescreen)

2024-05-02 16:10 UTC, C0DECYCLE commented on src/managers/SessionManager.ts
> +        if (response !== null) {
does it work like this? is the response null or the response body?

2024-05-02 16:20 UTC, C0DECYCLE commented on src/managers/SessionManager.ts
> +        if (response !== null) {
i tested it, response body is empty so you need to change the code

2024-05-02 16:21 UTC, C0DECYCLE commented on src/managers/SessionManager.ts
> +        if (response !== null) {
i would do it like this:
```
        if (!response.data) {
            return;
        }
        PlayerManager.saveId(response.data);
        location.pathname = "";
```

2024-05-02 16:22 UTC, C0DECYCLE requested changes

2024-05-02 16:22 UTC, C0DECYCLE commented on src/managers/SessionManager.ts
> +        return;
An empty return at the end of a function isn't required.

2024-05-04 09:19 UTC, paul891112 approved these changes
Nothing to add besides that

2024-05-05 16:08 UTC, C0DECYCLE approved these changes
LGTM

2024-05-06 07:11 UTC, merged